// <auto-generated />
// Polyfill: IsExternalInit for netstandard2.0 (enables C# 9 record types)
#if NETSTANDARD2_0
namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}
#endif
