using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Xml;
using DotnetPoi.SS.Xml;

namespace DotnetPoi.XWPF.UserModel;

/// <summary>
/// Represents a single style definition in a styles.xml file.
/// Corresponds to an Apache POI XWPFStyle.
/// </summary>
public sealed class XWPFStyle
{
    /// <summary>The style ID (e.g., "a", "1", "Heading1").</summary>
    public string? StyleId { get; internal set; }

    /// <summary>The display name (e.g., "Normal", "Heading 1").</summary>
    public string? Name { get; internal set; }

    /// <summary>The style type: "paragraph", "character", "table", "numbering", or "paragraphNumbering".</summary>
    public string? Type { get; internal set; }

    /// <summary>True if this is the default style of its type (w:default="1").</summary>
    public bool IsDefault { get; internal set; }

    /// <summary>Optional basedOn style ID.</summary>
    public string? BasedOn { get; internal set; }
}

/// <summary>
/// Manages styles.xml reading and generation for an XWPF document.
/// </summary>
public sealed class XWPFStyles
{
    private readonly List<XWPFStyle> _styles = new();

    /// <summary>Read-only collection of all parsed/generated styles.</summary>
    public IReadOnlyList<XWPFStyle> Styles => _styles;

    /// <summary>
    /// Retrieves a style by its styleId.
    /// </summary>
    public XWPFStyle? getStyle(string styleId)
    {
        if (styleId is null) return null;
        foreach (var s in _styles)
        {
            if (string.Equals(s.StyleId, styleId, StringComparison.Ordinal))
                return s;
        }
        return null;
    }

    /// <summary>
    /// Parses a styles.xml stream into the internal model.
    /// </summary>
    public void ReadStyles(Stream stream)
    {
        Guard.ThrowIfNull(stream, nameof(stream));
        using var reader = XmlReader.Create(stream, new XmlReaderSettings { IgnoreWhitespace = false });

        const string nsW = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";

        while (reader.Read())
        {
            if (reader.NodeType != XmlNodeType.Element) continue;
            if (reader.NamespaceURI != nsW) continue;

            if (reader.LocalName == "style")
            {
                var style = new XWPFStyle
                {
                    StyleId = reader.GetAttribute("w:styleId"),
                    Type = reader.GetAttribute("w:type"),
                    IsDefault = reader.GetAttribute("w:default") == "1"
                };

                // Read children of <w:style> to get <w:name> and <w:basedOn>
                if (!reader.IsEmptyElement)
                {
                    using var styleReader = reader.ReadSubtree();
                    while (styleReader.Read())
                    {
                        if (styleReader.NodeType != XmlNodeType.Element) continue;
                        if (styleReader.NamespaceURI != nsW) continue;

                        if (styleReader.LocalName == "name")
                        {
                            style.Name = styleReader.GetAttribute("w:val");
                        }
                        else if (styleReader.LocalName == "basedOn")
                        {
                            style.BasedOn = styleReader.GetAttribute("w:val");
                        }
                    }
                }

                _styles.Add(style);
            }
        }
    }

    /// <summary>
    /// Writes a complete default styles.xml to the writer, matching the structure
    /// generated by Apache POI's XWPFDocument (docDefaults with 11pt font, 1.15 line spacing,
    /// latent styles, plus Normal and Heading 1-3).
    /// </summary>
    public static void WriteDefaultStyles(PoiXmlWriter writer)
    {
        writer.WriteStartElement("w", "styles");
        writer.WriteAttributeString("xmlns:w", "http://schemas.openxmlformats.org/wordprocessingml/2006/main");
        writer.WriteAttributeString("xmlns:r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships");

        // docDefaults: default run properties (11pt font) and paragraph properties (spacing)
        writer.WriteStartElement("w", "docDefaults");

        // Run properties default: font size 11pt (22 half-pts)
        writer.WriteStartElement("w", "rPrDefault");
        writer.WriteStartElement("w", "rPr");
        WriteRPrFontSize(writer, 22); // 11pt = 22 half-pts
        writer.WriteEndElement(); // rPr
        writer.WriteEndElement(); // rPrDefault

        // Paragraph properties default: spacing after 200, line 276 (1.15 spacing)
        writer.WriteStartElement("w", "pPrDefault");
        writer.WriteStartElement("w", "pPr");
        writer.WriteStartElement("w", "spacing");
        writer.WriteAttributeString("w", "after", "200");
        writer.WriteAttributeString("w", "line", "276");
        writer.WriteAttributeString("w", "lineRule", "auto");
        writer.WriteEndElement(); // spacing
        writer.WriteEndElement(); // pPr
        writer.WriteEndElement(); // pPrDefault

        writer.WriteEndElement(); // docDefaults

        // Latent styles
        writer.WriteStartElement("w", "latentStyles");
        writer.WriteAttributeString("w", "defLockedState", "0");
        writer.WriteAttributeString("w", "defUIPriority", "99");
        writer.WriteAttributeString("w", "defSemiHidden", "1");
        writer.WriteAttributeString("w", "defUnhideWhenUsed", "1");
        writer.WriteAttributeString("w", "defQFormat", "0");
        writer.WriteAttributeString("w", "count", "267");

        // Style exceptions for key built-in styles (matching POI's output)
        WriteLatentStyleException(writer, "Normal", semiHidden: "0", uiPriority: "0", unhideWhenUsed: "0", qFormat: "1");
        WriteLatentStyleException(writer, "heading 1", semiHidden: "0", uiPriority: "9", unhideWhenUsed: "0", qFormat: "1");
        WriteLatentStyleException(writer, "heading 2", uiPriority: "9", qFormat: "1");
        WriteLatentStyleException(writer, "heading 3", uiPriority: "9", qFormat: "1");
        WriteLatentStyleException(writer, "heading 4", uiPriority: "9");
        WriteLatentStyleException(writer, "heading 5", uiPriority: "9");
        WriteLatentStyleException(writer, "heading 6", uiPriority: "9");
        WriteLatentStyleException(writer, "heading 7", uiPriority: "9");
        WriteLatentStyleException(writer, "heading 8", uiPriority: "9");
        WriteLatentStyleException(writer, "heading 9", uiPriority: "9");
        WriteLatentStyleException(writer, "Title", semiHidden: "0", uiPriority: "10");
        WriteLatentStyleException(writer, "Subtitle", semiHidden: "0", uiPriority: "11");
        WriteLatentStyleException(writer, "Strong", uiPriority: "22", qFormat: "1");
        WriteLatentStyleException(writer, "Emphasis", uiPriority: "20", qFormat: "1");
        WriteLatentStyleException(writer, "No Spacing", semiHidden: "0", uiPriority: "1", qFormat: "1");
        WriteLatentStyleException(writer, "List Paragraph", uiPriority: "34", qFormat: "1");
        WriteLatentStyleException(writer, "Quote", uiPriority: "29", qFormat: "1");
        WriteLatentStyleException(writer, "Intense Quote", uiPriority: "30", qFormat: "1");
        WriteLatentStyleException(writer, "Subtle Emphasis", uiPriority: "19", qFormat: "1");
        WriteLatentStyleException(writer, "Intense Emphasis", uiPriority: "21", qFormat: "1");
        WriteLatentStyleException(writer, "Subtle Reference", uiPriority: "31", qFormat: "1");
        WriteLatentStyleException(writer, "Intense Reference", uiPriority: "32", qFormat: "1");

        writer.WriteEndElement(); // latentStyles

        // Normal paragraph style (default paragraph style)
        WriteStyleEntry(writer, "Normal", type: "paragraph", default_: "1", name: "Normal",
            uiPriority: "0", semiHidden: "0", unhideWhenUsed: "0", qFormat: "1",
            rPrOptions: (szVal: "24", szCsVal: "24", bold: null, italic: null, color: null, themeColor: null, themeShade: null, themeDark: null, kern: null, spacingVal: null, spacingCsVal: null),
            pPrOptions: (spacingBefore: null, spacingAfter: "0", spacingLine: "240", spacingLineRule: "auto", keepNext: null, keepLines: null, outlineLvl: null));

        // Heading 1
        WriteStyleEntry(writer, "heading 1", type: "paragraph", name: "Heading 1",
            basedOn: "Normal", next: "Normal",
            uiPriority: "9", qFormat: "1",
            rPrOptions: (szVal: "32", szCsVal: "32", bold: "on", italic: null, color: "2F5496",
                themeColor: "accent1", themeShade: "BF", themeDark: null,
                kern: "0",
                spacingVal: "0", spacingCsVal: "0"),
            pPrOptions: (spacingBefore: "480", spacingAfter: "0", spacingLine: null, spacingLineRule: null,
                keepNext: null, keepLines: null,
                outlineLvl: "0"));

        // Heading 2
        WriteStyleEntry(writer, "heading 2", type: "paragraph", name: "Heading 2",
            basedOn: "Normal", next: "Normal",
            uiPriority: "9", qFormat: "1",
            rPrOptions: (szVal: "28", szCsVal: "28", bold: "on", italic: "on", color: "2F5496",
                themeColor: "accent1", themeShade: "BF", themeDark: null,
                kern: "0",
                spacingVal: "0", spacingCsVal: "0"),
            pPrOptions: (spacingBefore: "280", spacingAfter: "0", spacingLine: null, spacingLineRule: null,
                keepNext: null, keepLines: null,
                outlineLvl: "1"));

        // Heading 3
        WriteStyleEntry(writer, "heading 3", type: "paragraph", name: "Heading 3",
            basedOn: "Normal", next: "Normal",
            uiPriority: "9", qFormat: "1",
            rPrOptions: (szVal: "24", szCsVal: "24", bold: "on", italic: null, color: "1F3864",
                themeColor: "accent1", themeShade: null, themeDark: "25",
                kern: "0",
                spacingVal: "0", spacingCsVal: "0"),
            pPrOptions: (spacingBefore: "200", spacingAfter: "0", spacingLine: null, spacingLineRule: null,
                keepNext: null, keepLines: null,
                outlineLvl: "2"));

        writer.WriteEndElement(); // styles
    }

    private static void WriteLatentStyleException(PoiXmlWriter writer, string name,
        string? semiHidden = null, string? uiPriority = null,
        string? unhideWhenUsed = null, string? qFormat = null)
    {
        writer.WriteStartElement("w", "lsdException");
        writer.WriteAttributeString("w", "name", name);
        if (semiHidden is not null)
            writer.WriteAttributeString("w", "semiHidden", semiHidden);
        if (uiPriority is not null)
            writer.WriteAttributeString("w", "uiPriority", uiPriority);
        if (unhideWhenUsed is not null)
            writer.WriteAttributeString("w", "unhideWhenUsed", unhideWhenUsed);
        if (qFormat is not null)
            writer.WriteAttributeString("w", "qFormat", qFormat);
        writer.WriteEndElement();
    }

    /// <summary>
    /// Writes a single <w:style> entry with configurable run and paragraph properties.
    /// </summary>
    private static void WriteStyleEntry(PoiXmlWriter writer, string styleId,
        string type, string name,
        string? default_ = null, string? basedOn = null, string? next = null,
        string? uiPriority = null, string? semiHidden = null,
        string? unhideWhenUsed = null, string? qFormat = null,
        (string? szVal, string? szCsVal, string? bold, string? italic,
            string? color, string? themeColor, string? themeShade, string? themeDark,
            string? kern, string? spacingVal, string? spacingCsVal)? rPrOptions = null,
        (string? spacingBefore, string? spacingAfter, string? spacingLine, string? spacingLineRule,
            string? keepNext, string? keepLines,
            string? outlineLvl)? pPrOptions = null)
    {
        writer.WriteStartElement("w", "style");
        writer.WriteAttributeString("w", "type", type);
        writer.WriteAttributeString("w", "styleId", styleId);
        if (default_ is not null)
            writer.WriteAttributeString("w", "default", default_);

        // Style name
        writer.WriteStartElement("w", "name");
        writer.WriteAttributeString("w", "val", name);
        writer.WriteEndElement();

        // basedOn
        if (basedOn is not null)
        {
            writer.WriteStartElement("w", "basedOn");
            writer.WriteAttributeString("w", "val", basedOn);
            writer.WriteEndElement();
        }

        // next (for headings)
        if (next is not null)
        {
            writer.WriteStartElement("w", "next");
            writer.WriteAttributeString("w", "val", next);
            writer.WriteEndElement();
        }

        // qFormat
        if (qFormat is not null)
        {
            writer.WriteStartElement("w", "qFormat");
            writer.WriteEndElement();
        }

        // uiPriority
        if (uiPriority is not null)
        {
            writer.WriteStartElement("w", "uiPriority");
            writer.WriteAttributeString("w", "val", uiPriority);
            writer.WriteEndElement();
        }

        // semiHidden
        if (semiHidden is not null)
        {
            writer.WriteStartElement("w", "semiHidden");
            writer.WriteAttributeString("w", "val", semiHidden);
            writer.WriteEndElement();
        }

        // unhideWhenUsed
        if (unhideWhenUsed is not null)
        {
            writer.WriteStartElement("w", "unhideWhenUsed");
            writer.WriteAttributeString("w", "val", unhideWhenUsed);
            writer.WriteEndElement();
        }

        // Run properties (rPr)
        if (rPrOptions is not null)
        {
            var rp = rPrOptions.Value;
            bool hasAny = rp.szVal is not null || rp.bold is not null || rp.italic is not null
                || rp.color is not null || rp.themeColor is not null || rp.kern is not null
                || rp.spacingVal is not null;
            if (hasAny)
            {
                writer.WriteStartElement("w", "rPr");

                if (rp.bold is not null)
                {
                    writer.WriteStartElement("w", "b");
                    writer.WriteAttributeString("w", "val", rp.bold);
                    writer.WriteEndElement();
                }

                if (rp.italic is not null)
                {
                    writer.WriteStartElement("w", "i");
                    writer.WriteAttributeString("w", "val", rp.italic);
                    writer.WriteEndElement();
                }

                if (rp.color is not null)
                {
                    writer.WriteStartElement("w", "color");
                    writer.WriteAttributeString("w", "val", rp.color);
                    if (rp.themeColor is not null)
                        writer.WriteAttributeString("w", "themeColor", rp.themeColor);
                    if (rp.themeShade is not null)
                        writer.WriteAttributeString("w", "themeShade", rp.themeShade);
                    if (rp.themeDark is not null)
                        writer.WriteAttributeString("w", "themeDark", rp.themeDark);
                    writer.WriteEndElement();
                }

                if (rp.szVal is not null)
                {
                    writer.WriteStartElement("w", "sz");
                    writer.WriteAttributeString("w", "val", rp.szVal);
                    writer.WriteEndElement();
                }

                if (rp.szCsVal is not null)
                {
                    writer.WriteStartElement("w", "szCs");
                    writer.WriteAttributeString("w", "val", rp.szCsVal);
                    writer.WriteEndElement();
                }

                if (rp.kern is not null)
                {
                    writer.WriteStartElement("w", "kern");
                    writer.WriteAttributeString("w", "val", rp.kern);
                    writer.WriteEndElement();
                }

                if (rp.spacingVal is not null)
                {
                    writer.WriteStartElement("w", "spacing");
                    writer.WriteAttributeString("w", "val", rp.spacingVal);
                    writer.WriteAttributeString("w", "csVal", rp.spacingCsVal ?? "0");
                    writer.WriteEndElement();
                }

                writer.WriteEndElement(); // rPr
            }
        }

        // Paragraph properties (pPr)
        if (pPrOptions is not null)
        {
            var pp = pPrOptions.Value;
            bool hasAny = pp.spacingBefore is not null || pp.spacingAfter is not null
                || pp.spacingLine is not null || pp.keepNext is not null
                || pp.keepLines is not null || pp.outlineLvl is not null;
            if (hasAny)
            {
                writer.WriteStartElement("w", "pPr");

                if (pp.keepNext is not null)
                {
                    writer.WriteStartElement("w", "keepNext");
                    writer.WriteEndElement();
                }

                if (pp.keepLines is not null)
                {
                    writer.WriteStartElement("w", "keepLines");
                    writer.WriteEndElement();
                }

                if (pp.spacingBefore is not null || pp.spacingAfter is not null
                    || pp.spacingLine is not null)
                {
                    writer.WriteStartElement("w", "spacing");
                    if (pp.spacingBefore is not null)
                        writer.WriteAttributeString("w", "before", pp.spacingBefore);
                    if (pp.spacingAfter is not null)
                        writer.WriteAttributeString("w", "after", pp.spacingAfter);
                    if (pp.spacingLine is not null)
                    {
                        writer.WriteAttributeString("w", "line", pp.spacingLine);
                        writer.WriteAttributeString("w", "lineRule", pp.spacingLineRule ?? "auto");
                    }
                    writer.WriteEndElement();
                }

                if (pp.outlineLvl is not null)
                {
                    writer.WriteStartElement("w", "outlineLvl");
                    writer.WriteAttributeString("w", "val", pp.outlineLvl);
                    writer.WriteEndElement();
                }

                writer.WriteEndElement(); // pPr
            }
        }

        writer.WriteEndElement(); // style
    }

    /// <summary>
    /// Writes a font size element (sz) and its complex-script counterpart (szCs).
    /// </summary>
    private static void WriteRPrFontSize(PoiXmlWriter writer, int halfPtSize)
    {
        var val = halfPtSize.ToString(CultureInfo.InvariantCulture);
        writer.WriteStartElement("w", "sz");
        writer.WriteAttributeString("w", "val", val);
        writer.WriteEndElement();
        writer.WriteStartElement("w", "szCs");
        writer.WriteAttributeString("w", "val", val);
        writer.WriteEndElement();
    }
}
