using System.IO.Compression;
using DotnetPoi.HSSF.UserModel;
using DotnetPoi.POIFS.Crypt;
using DotnetPoi.XSSF.UserModel;
using DotnetPoi.XSLF.UserModel;
using DotnetPoi.XWPF.UserModel;

const string password = "f";

var repoRoot = FindRepositoryRoot(AppContext.BaseDirectory);
var outputDirectory = args.Length > 0
    ? Path.GetFullPath(args[0], repoRoot)
    : Path.Combine(repoRoot, "tools", "manual-verification", "generated-documents");
Directory.CreateDirectory(outputDirectory);

var testFilesDirectory = Path.Combine(repoRoot, "tests", "test-files");
var imageBytes = File.ReadAllBytes(Path.Combine(testFilesDirectory, "image.jpg"));
var xlsmVba = ReadZipEntry(Path.Combine(testFilesDirectory, "example.xlsm"), "xl/vbaProject.bin");
var docmVba = ReadZipEntry(Path.Combine(testFilesDirectory, "example.docm"), "word/vbaProject.bin");
var pptmVba = ReadZipEntry(Path.Combine(testFilesDirectory, "example.pptm"), "ppt/vbaProject.bin");

var outputs = new List<(string Label, string Path, string? Password)>();

outputs.Add(("xlsx", Path.Combine(outputDirectory, "manual-simple.xlsx"), null));
CreateXlsx(outputs[^1].Path, includeMacros: false, vbaProject: null);

outputs.Add(("xlsm", Path.Combine(outputDirectory, "manual-simple.xlsm"), null));
CreateXlsx(outputs[^1].Path, includeMacros: true, xlsmVba);

outputs.Add(("encrypted xlsx", Path.Combine(outputDirectory, "manual-encrypted.xlsx"), password));
CreateEncryptedXlsx(outputs[^1].Path);

outputs.Add(("pptx", Path.Combine(outputDirectory, "manual-simple.pptx"), null));
CreatePptx(outputs[^1].Path, includeMacros: false, vbaProject: null, imageBytes);

outputs.Add(("pptm", Path.Combine(outputDirectory, "manual-simple.pptm"), null));
CreatePptx(outputs[^1].Path, includeMacros: true, pptmVba, imageBytes);

outputs.Add(("encrypted pptx", Path.Combine(outputDirectory, "manual-encrypted.pptx"), password));
CreateEncryptedPptx(outputs[^1].Path);

outputs.Add(("docx", Path.Combine(outputDirectory, "manual-simple.docx"), null));
CreateDocx(outputs[^1].Path, includeMacros: false, vbaProject: null);

outputs.Add(("docm", Path.Combine(outputDirectory, "manual-simple.docm"), null));
CreateDocx(outputs[^1].Path, includeMacros: true, docmVba);

outputs.Add(("encrypted docx", Path.Combine(outputDirectory, "manual-encrypted.docx"), password));
CreateEncryptedDocx(outputs[^1].Path);

outputs.Add(("xls", Path.Combine(outputDirectory, "manual-simple.xls"), null));
CreateXls(outputs[^1].Path);

Console.WriteLine("Manual verification documents generated:");
foreach (var output in outputs)
{
    var info = new FileInfo(output.Path);
    var passwordNote = output.Password is null ? "" : $" password={output.Password}";
    Console.WriteLine($"  {output.Label,-16} {info.Length,8} bytes  {output.Path}{passwordNote}");
}

static void CreateXlsx(string outputPath, bool includeMacros, byte[]? vbaProject)
{
    using var workbook = new XSSFWorkbook();
    var sheet = workbook.createSheet(includeMacros ? "MacroBook" : "Workbook");

    var header = sheet.createRow(0);
    header.createCell(0).setCellValue("Manual verification");
    header.createCell(1).setCellValue(includeMacros ? "xlsm" : "xlsx");

    var row = sheet.createRow(1);
    row.createCell(0).setCellValue("Generated by dotnet-poi");
    row.createCell(1).setCellValue(DateTime.UtcNow.ToString("yyyy-MM-dd"));

    var numberRow = sheet.createRow(2);
    numberRow.createCell(0).setCellValue("Value");
    numberRow.createCell(1).setCellValue(123.45);

    sheet.setColumnWidth(0, 28 * 256);
    sheet.setColumnWidth(1, 18 * 256);

    if (includeMacros)
    {
        workbook.setVBAProject(vbaProject ?? throw new ArgumentNullException(nameof(vbaProject)));
    }

    using var output = File.Create(outputPath);
    workbook.write(output);
}

static void CreateEncryptedXlsx(string outputPath)
{
    using var workbook = new XSSFWorkbook();
    var sheet = workbook.createSheet("Encrypted");
    sheet.createRow(0).createCell(0).setCellValue("Encrypted xlsx");
    sheet.createRow(1).createCell(0).setCellValue("password");
    sheet.getRow(1)!.createCell(1).setCellValue(password);

    using (var output = File.Create(outputPath))
    {
        workbook.writeEncrypted(output, password);
    }

    VerifyEncryptedPackage(outputPath, bytes =>
    {
        using var decrypted = new XSSFWorkbook(new MemoryStream(bytes));
        AssertText("Encrypted xlsx", decrypted.getSheet("Encrypted")!.getRow(0)!.getCell(0)!.getStringCellValue(), "encrypted xlsx");
    });
}

static void CreatePptx(string outputPath, bool includeMacros, byte[]? vbaProject, byte[] imageBytes)
{
    using var presentation = new XMLSlideShow();

    var titleSlide = presentation.createSlide();
    var titleBox = titleSlide.createTextBox();
    titleBox.setAnchor(685_800, 457_200, 7_315_200, 914_400);
    var title = titleBox.addParagraph().addRun(includeMacros ? "Manual pptm" : "Manual pptx");
    title.Bold = true;
    title.FontSize = 28;

    var imageIndex = presentation.addPicture(imageBytes, XSLFPictureData.PICTURE_TYPE_JPEG);
    var pictureSlide = presentation.createSlide();
    var picture = presentation.createPicture(pictureSlide, imageIndex);
    picture.setAnchor(914_400, 914_400, 3_657_600, 2_743_200);
    picture.setRotation(5);

    if (includeMacros)
    {
        presentation.setVBAProject(vbaProject ?? throw new ArgumentNullException(nameof(vbaProject)));
    }

    using var output = File.Create(outputPath);
    presentation.write(output);
}

static void CreateEncryptedPptx(string outputPath)
{
    using var presentation = new XMLSlideShow();
    var slide = presentation.createSlide();
    var titleBox = slide.createTextBox();
    titleBox.setAnchor(685_800, 685_800, 7_315_200, 914_400);
    titleBox.addParagraph().addRun("Encrypted pptx");

    using (var output = File.Create(outputPath))
    {
        presentation.writeEncrypted(output, password);
    }

    VerifyEncryptedPackage(outputPath, bytes =>
    {
        using var decrypted = new XMLSlideShow(new MemoryStream(bytes));
        AssertText("Encrypted pptx", decrypted.getSlides()[0].getAutoShapes()[0].Paragraphs[0].getPlainText(), "encrypted pptx");
    });
}

static void CreateDocx(string outputPath, bool includeMacros, byte[]? vbaProject)
{
    using var document = new XWPFDocument();

    var heading = document.createParagraph();
    var headingRun = heading.createRun();
    headingRun.setText(includeMacros ? "Manual docm" : "Manual docx");
    headingRun.setBold(true);
    headingRun.setFontSize(18);

    var paragraph = document.createParagraph();
    paragraph.createRun().setText("Generated by dotnet-poi for manual verification.");

    var table = document.createTable();
    AddDocxRow(table, "Type", includeMacros ? "docm" : "docx");
    AddDocxRow(table, "Status", "simple document");

    if (includeMacros)
    {
        document.setVBAProject(vbaProject ?? throw new ArgumentNullException(nameof(vbaProject)));
    }

    using var output = File.Create(outputPath);
    document.write(output);
}

static void CreateEncryptedDocx(string outputPath)
{
    using var document = new XWPFDocument();
    document.createParagraph().createRun().setText("Encrypted docx");

    using var package = new MemoryStream();
    document.write(package);

    WriteEncryptedPackage(package.ToArray(), outputPath);

    VerifyEncryptedPackage(outputPath, bytes =>
    {
        using var decrypted = new XWPFDocument(new MemoryStream(bytes));
        AssertText("Encrypted docx", decrypted.getParagraphs()[0].getText(), "encrypted docx");
    });
}

static void CreateXls(string outputPath)
{
    using var workbook = new HSSFWorkbook();
    var sheet = workbook.createSheet("Workbook");
    var header = sheet.createRow(0);
    header.createCell(0).setCellValue("Manual verification");
    header.createCell(1).setCellValue("xls");

    var row = sheet.createRow(1);
    row.createCell(0).setCellValue("Legacy binary workbook");
    row.createCell(1).setCellValue(97.2003);

    using var output = File.Create(outputPath);
    workbook.write(output);
}

static void AddDocxRow(XWPFTable table, string left, string right)
{
    var row = table.createRow();
    row.createCell().addParagraph().createRun().setText(left);
    row.createCell().addParagraph().createRun().setText(right);
}

static void WriteEncryptedPackage(byte[] packageBytes, string outputPath)
{
    var info = new EncryptionInfo(EncryptionMode.agile);
    info.Encryptor.confirmPassword(password);
    using var output = File.Create(outputPath);
    info.Encryptor.encryptPackage(packageBytes, output);
}

static void VerifyEncryptedPackage(string outputPath, Action<byte[]> verifyDecryptedPackage)
{
    using var encrypted = File.OpenRead(outputPath);
    var info = new EncryptionInfo(encrypted);
    if (!info.Decryptor.verifyPassword(password))
    {
        throw new InvalidOperationException($"Could not verify password for {outputPath}.");
    }

    verifyDecryptedPackage(info.Decryptor.getData());
}

static byte[] ReadZipEntry(string packagePath, string entryName)
{
    using var stream = File.OpenRead(packagePath);
    using var archive = new ZipArchive(stream, ZipArchiveMode.Read);
    var entry = archive.GetEntry(entryName)
        ?? throw new InvalidDataException($"{packagePath} does not contain {entryName}.");
    using var entryStream = entry.Open();
    using var memory = new MemoryStream();
    entryStream.CopyTo(memory);
    return memory.ToArray();
}

static void AssertText(string expected, string actual, string label)
{
    if (!string.Equals(expected, actual, StringComparison.Ordinal))
    {
        throw new InvalidOperationException($"{label}: expected '{expected}', got '{actual}'.");
    }
}

static string FindRepositoryRoot(string startDirectory)
{
    var directory = new DirectoryInfo(startDirectory);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "DotnetPOI.sln")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new DirectoryNotFoundException("Could not locate the dotnet-poi repository root.");
}
