// <auto-generated />
// Polyfills for netstandard2.0 compatibility

#if NETSTANDARD2_0
namespace System.Runtime.CompilerServices
{
    /// <summary>Enables C# 9 record types on netstandard2.0.</summary>
    internal static class IsExternalInit { }
}
#endif

// Polyfill: AsSpan extension on Span<T> and ReadOnlySpan<T>.
// .NET 5+ has AsSpan(int) only for T[] and string, not for Span<T> / ReadOnlySpan<T>.
internal static class SpanExtensions
{
    public static Span<T> AsSpan<T>(this Span<T> span, int start) => span.Slice(start);
    public static Span<T> AsSpan<T>(this Span<T> span, int start, int length) => span.Slice(start, length);
    public static ReadOnlySpan<T> AsSpan<T>(this ReadOnlySpan<T> span, int start) => span.Slice(start);
    public static ReadOnlySpan<T> AsSpan<T>(this ReadOnlySpan<T> span, int start, int length) => span.Slice(start, length);
}

namespace DotnetPoi
{
    /// <summary>
    /// Polyfill for .NET 6+ ArgumentNullException.ThrowIfNull.
    /// Works on both net8.0 and netstandard2.0.
    /// </summary>
    internal static class Guard
    {
        internal static void ThrowIfNull(object argument, string paramName)
        {
            if (argument is null)
                throw new ArgumentNullException(paramName);
        }
    }

    /// <summary>
    /// Crypto polyfills for netstandard2.0 compatibility.
    /// .NET 6+ APIs like RandomNumberGenerator.Fill(Span), SHA1.HashData, CryptographicOperations
    /// are not available on netstandard2.0.
    /// </summary>
    internal static class NetsStandardCrypto
    {
#if NETSTANDARD2_0
        internal static void Fill(Span<byte> buffer)
        {
            var tmp = new byte[buffer.Length];
            System.Security.Cryptography.RandomNumberGenerator.Create().GetBytes(tmp);
            tmp.CopyTo(buffer);
        }

        internal static byte[] HashSha1(ReadOnlySpan<byte> data)
        {
            using var sha1 = System.Security.Cryptography.SHA1.Create();
            return sha1.ComputeHash(data.ToArray());
        }

        internal static bool FixedTimeEquals(byte[] left, byte[] right)
        {
            if (left.Length != right.Length) return false;
            var diff = 0;
            for (var i = 0; i < left.Length; i++)
                diff |= left[i] ^ right[i];
            return diff == 0;
        }
#else
        internal static void Fill(Span<byte> buffer) => System.Security.Cryptography.RandomNumberGenerator.Fill(buffer);
        internal static byte[] HashSha1(ReadOnlySpan<byte> data) => System.Security.Cryptography.SHA1.HashData(data);
        internal static bool FixedTimeEquals(byte[] left, byte[] right) => System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(left, right);
#endif
    }
}
