using DotnetPoi.XWPF.UserModel;

var repoRoot = FindRepositoryRoot(AppContext.BaseDirectory);
var outputDirectory = Path.Combine(repoRoot, "examples", "output");
Directory.CreateDirectory(outputDirectory);

var outputPath = Path.Combine(outputDirectory, "phase3_2-docx-example.docx");

WriteDocument(outputPath);
ReadAndAssertDocument(outputPath);

Console.WriteLine("Phase 3.2 docx example passed.");
Console.WriteLine($"dotnet-poi wrote: {outputPath}");

static void WriteDocument(string outputPath)
{
    using var doc = new XWPFDocument();

    // Paragraph 1: bold heading
    var heading = doc.createParagraph();
    var h1 = heading.createRun();
    h1.setText("dotnet-poi XWPF Example");
    h1.setBold(true);

    // Paragraph 2: italic subtitle
    var subtitle = doc.createParagraph();
    var s1 = subtitle.createRun();
    s1.setText("Phase 3.2 — docx support");
    s1.setItalic(true);

    // Paragraph 3: plain body text
    var body = doc.createParagraph();
    body.createRun().setText("This document was generated by dotnet-poi.");

    // Paragraph 4: inline image (1×1 px PNG) rotated 45°
    var imagePara = doc.createParagraph();
    var imageRun = imagePara.createRun();
    var picture = imageRun.addPicture(
        OneByOnePng(),
        XWPFPictureData.PICTURE_TYPE_PNG,
        "sample.png",
        width:  914400,   // 1 inch in EMU
        height: 914400);
    picture.setRotation(45.0);

    using var stream = File.Create(outputPath);
    doc.write(stream);
}

static void ReadAndAssertDocument(string path)
{
    using var stream = File.OpenRead(path);
    using var doc = new XWPFDocument(stream);

    var paragraphs = doc.getParagraphs();
    AssertInt(4, paragraphs.Count, "paragraph count");

    // Paragraph 1 — bold
    var run1 = paragraphs[0].getRuns()[0];
    AssertString("dotnet-poi XWPF Example", run1.getText(0) ?? "", "paragraph 1 text");
    if (!run1.isBold())
        throw new InvalidOperationException("paragraph 1 run should be bold");

    // Paragraph 2 — italic
    var run2 = paragraphs[1].getRuns()[0];
    AssertString("Phase 3.2 — docx support", run2.getText(0) ?? "", "paragraph 2 text");
    if (!run2.isItalic())
        throw new InvalidOperationException("paragraph 2 run should be italic");

    // Paragraph 3 — plain
    AssertString("This document was generated by dotnet-poi.",
        paragraphs[2].getText(), "paragraph 3 text");

    // Paragraph 4 — image with rotation
    var imageRun = paragraphs[3].getRuns()[0];
    var pics = imageRun.getEmbeddedPictures();
    AssertInt(1, pics.Count, "embedded picture count");
    AssertDouble(45.0, pics[0].getRotation(), "picture rotation");

    // Picture data available at document level
    AssertInt(1, doc.getAllPictures().Count, "total picture count");
    AssertInt(XWPFPictureData.PICTURE_TYPE_PNG, doc.getAllPictures()[0].getPictureType(), "picture type");
}

static byte[] OneByOnePng()
{
    return Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO2O8WcAAAAASUVORK5CYII=");
}

static void AssertString(string expected, string actual, string label)
{
    if (!string.Equals(expected, actual, StringComparison.Ordinal))
        throw new InvalidOperationException($"{label}: expected '{expected}', got '{actual}'.");
}

static void AssertInt(int expected, int actual, string label)
{
    if (expected != actual)
        throw new InvalidOperationException($"{label}: expected {expected}, got {actual}.");
}

static void AssertDouble(double expected, double actual, string label)
{
    if (Math.Abs(expected - actual) > 1e-6)
        throw new InvalidOperationException($"{label}: expected {expected}, got {actual}.");
}

static string FindRepositoryRoot(string startDirectory)
{
    var directory = new DirectoryInfo(startDirectory);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "DotnetPOI.sln")))
            return directory.FullName;
        directory = directory.Parent;
    }
    throw new DirectoryNotFoundException("Could not locate the dotnet-poi repository root.");
}
